### ISSUE TITLE
Differences in variants between v1.8.0 and v2.0.4 

### ISSUE THREAD

**Issue by jil24** [MissionBio/mosaic#10]
I have a DNA+Protein dataset composed of 7 merged samples that I had previously been analyzing with mosaic version 1.8.0.

As I am trying out version 2.0.4 I find that the vast majority of the variants that I know are in the dataset do not seem to be recognized; before any filtering is applied.

The difference is quite dramatic:
### Version 1.8.0
```
print(len(Merged_Samples.dna.ids()))
```
Result: `65151`

### Version 2.0.4
```
for sample in Merged_Samples.samples:
	print(len(sample.dna.ids()))
```

Result: `44
44
44
44
44
44
44`

Is there some kind of implicit filtering going on? If so, how can it be disabled (I know that some variants have been filtered out that are real and confirmed with orthogonal assays)

**Comment by KKJSP** [comment]
@jil24 The default value of the `apply_filter` parameter in [missionbio.mosaic.io.load](https://missionbio.github.io/mosaic/pages/functions/missionbio.mosaic.io.load.html#missionbio.mosaic.io.load) has been changed from `False` in v1.x to `True` in v2.x. All the variants will be loaded when `apply_filter=False` is passed.

**Comment by jil24** [comment]
Perfect, thank you
