### ISSUE TITLE
Guide to install Mosaic

### ISSUE THREAD

**Issue by mdbabumiamssm** [MissionBio/mosaic#12]
For some strange reason, conda link ( https://anaconda.org/missionbio/missionbio.mosaic ) didn't work for me. After several repetitive effort, I gave up ! 
The i started installing by creating new environment. Follow the images for details. Also, You need to specify the version of Mosaic, otherwise it doesn't install . I used Anaconda3 environment on this purpose. Feel free text me if any trouble comes.
<img width="859" alt="tapestri installation 4" src="https://user-images.githubusercontent.com/116982937/216469393-83994c87-9f06-4279-b9d5-8e462a88ea25.png">
![tapestri installation 1](https://user-images.githubusercontent.com/116982937/216469394-70a9c956-eb47-4f74-9a2e-3aea5f027d16.png)
![tapestri installation 2](https://user-images.githubusercontent.com/116982937/216469397-e045af3b-d814-418b-a79d-c0b7918295cd.png)
![tapestri installation 3](https://user-images.githubusercontent.com/116982937/216469399-d71fe894-df98-453f-9e3b-2889d438c498.png)

**Comment by KKJSP** [comment]
Mosaic should now be installed using installers - https://missionbio.github.io/mosaic/pages/install.html#installer-preferred

Feel free to create a new ticket if there are any issues.

**Comment by mdbabumiamssm** [comment]
@KKJSP 
I have tried installing using suggested installer ; Unfortunately, it only created new mosaic conda environment in windows, didn't install missionbio... 
Also, can you make linux installation instructions separate and more specific ? 
Thanks

**Comment by KKJSP** [comment]
@mdbabumiamssm for now it only creates an environment from which the notebooks can be launched. There isn't a separate GUI available for mosaic.

For linux, just running the shell script using `bash <path to installer>` is sufficient to create the new environment.
