### ISSUE TITLE
Mosaic installation issue

### ISSUE THREAD

**Issue by drafzalsyed** [MissionBio/mosaic#13]
Hi
I am trying to install mosaic using this `conda create --name mosaic -c missionbio -c plotly -c conda-forge missionbio.mosaic notebook`
then it gives these messages

_Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment:_
Then it hangs up on this. I tried different things and several times, but in vain. Could you please help me figure out the problem?
Thanks

**Comment by KKJSP** [comment]
1. Please try using the latest [solver from from conda](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community). To use the new solver, update conda in your base environment:

    `conda update -n base conda`

    To install and set the new solver, run the following commands:
    ```
    conda install -n base conda-libmamba-solver
    conda config --set solver libmamba
    ```
2. Set the conda channel priority to strict:
`conda config --set channel_priority strict`


Then try running the installation command again. It should be considerably faster.

**Comment by drafzalsyed** [comment]
Hey, thanks for the reply. I somehow managed to install it. I am actually working on Jupyterlab on our local cluster. Could you please tell me where can I find the notebook template for masaic v2?

**Comment by KKJSP** [comment]
Mosaic should now be installed using installers - https://missionbio.github.io/mosaic/pages/install.html#installer-preferred
