### ISSUE TITLE
By what criteria does the load function filter dna variants?

### ISSUE THREAD

**Issue by msteph11** [MissionBio/mosaic#16]
Hello,

I've been using the apply_filter option for the load function (https://missionbio.github.io/mosaic/pages/functions/missionbio.mosaic.io.load.html), as the resulting object is too big otherwise. I was wondering what criteria is being used to filter the variants? I can't seem to find it in the documentation.

Thanks

**Comment by KKJSP** [comment]
@msteph11 The [load](https://missionbio.github.io/mosaic/autosummary_pages/functions/missionbio.mosaic.io.load.html#missionbio.mosaic.io.load) functions documentation page has been updated with more details.

```
filter_variants:
If False, then all the variants are loaded. If True then only the filtered dna variants
are loaded. The filtered DNA variants are those that pass the Dna.filter_variants() function.
This list can be obtained by loading all variants by setting filter_variants=False and
then running Dna.filter_variants() on it. Information about the default filtered variants is
stored in the filtered column attribute of the Dna object.
```

Note: `apply_filter` in v2 has been renamed to `filter_variants` in v3 of mosaic. The above doc page is for v3.

**Comment by KKJSP** [comment]
Closing this for now. Feel free to comment if further clarification is required.
