### ISSUE TITLE
COMPASS issue

### ISSUE THREAD

**Issue by LiangMingxuan00** [MissionBio/mosaic#18]
Hi, thanks for your work on this tool.

I'm trying to run the COMPASS following the MOSAIC tutorial. But I'm find there is an error when I plot the phylogeny tree.

import missionbio.mosaic as ms
**_from missionbio.mosaic.algorithms.compass import COMPASS
sample = ms.load_example_dataset("2 PBMC mix")
compass = COMPASS(sample, somatic_variants=["chr4:55599436:T/C", "chr5:170837457:A/G"])
compass.run()_**
These codes works normally.

When I run **_compass.plot_tree()_**, it return with error message:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[39], line 1
----> 1 compass.plot_tree()

File ~/anaconda3new/envs/mosaic1/lib/python3.9/site-packages/missionbio/mosaic/algorithms/compass.py:253, in COMPASS.plot_tree(self)
    243 def plot_tree(self) -> go.Figure:
    244     """
    245     Generate a tree plot for the phylogeny
    246 
   (...)
    250         The plot generated by `TreeGraph.plot`
    251     """
--> 253     node_description = self.node_descriptions(percent=True)
    254     labels = np.array([n["name"] for n in self.tree_["nodes"]])
    255     parents = [n["parent"] if n["parent"] != "-" else None for n in self.tree_["nodes"]]

File ~/anaconda3new/envs/mosaic1/lib/python3.9/site-packages/missionbio/mosaic/algorithms/compass.py:293, in COMPASS.node_descriptions(self, percent)
    290 if len(node[snv]) != 0:
    291     desc += "\n".join(node[snv])
--> 293 if len(node[cnloh]) != 0:
    294     desc += f"\n{cnloh}: "
    295     desc += ", ".join(node[cnloh])

KeyError: 'CNLOH'

Could you help to solve this problem? Many thanks in advance!

Best,
Mingxuan

**Comment by KKJSP** [comment]
Could you share the value of `compass.tree_`?

**Comment by LiangMingxuan00** [comment]
> Could you share the value of `compass.tree_`?

Hi,

compass.tree_

{'nodes': [{'name': '3', 'parent': '-', 'SNV': [], 'CNA': []},
  {'name': '1', 'parent': '2', 'SNV': ['NPM1 (c.847-74A-G)'], 'CNA': []},
  {'name': '2', 'parent': '3', 'SNV': ['KIT (c.2484+78T-C)'], 'CNA': []}]}

**Comment by KKJSP** [comment]
Did you manually install COMPASS? The functions in Mosaic work with a slightly older version of COMPASS. It can be [found here](https://github.com/cbg-ethz/COMPASS/tree/757ce5b72993ea04e8f11ccaf3e5a25b16d62571). That version of COMPASS uses `SNV`, `CNLOH`, and `CNV` as keys to describe the nodes, unlike the `SNV` and `CNA` seen in your output.

You have two options:
1. Install mosaic using the installer found here - https://portal.missionbio.com/
2. If you really want to use mosaic for the visualizations convert the output to something compatible with mosaic. Something like the following:
```
compass.tree_ = {'nodes': [{'name': '3', 'parent': '-', 'SNV': [], 'CNV': [], 'CNLOH': []},
{'name': '1', 'parent': '2', 'SNV': ['NPM1 (c.847-74A-G)'], 'CNV': [], 'CNLOH': []},
{'name': '2', 'parent': '3', 'SNV': ['KIT (c.2484+78T-C)'], 'CNV': [], 'CNLOH': []}]}
compass. plot_tree()
```

I would recommend the former.

**Comment by LiangMingxuan00** [comment]
> Did you manually install COMPASS? The functions in Mosaic work with a slightly older version of COMPASS. It can be [found here](https://github.com/cbg-ethz/COMPASS/tree/757ce5b72993ea04e8f11ccaf3e5a25b16d62571). That version of COMPASS uses `SNV`, `CNLOH`, and `CNV` as keys to describe the nodes, unlike the `SNV` and `CNA` seen in your output.
> 
> You have two options:
> 
> 1. Install mosaic using the installer found here - https://portal.missionbio.com/
> 2. If you really want to use mosaic for the visualizations convert the output to something compatible with mosaic. Something like the following:
> 
> ```
> compass.tree_ = {'nodes': [{'name': '3', 'parent': '-', 'SNV': [], 'CNV': [], 'CNLOH': []},
> {'name': '1', 'parent': '2', 'SNV': ['NPM1 (c.847-74A-G)'], 'CNV': [], 'CNLOH': []},
> {'name': '2', 'parent': '3', 'SNV': ['KIT (c.2484+78T-C)'], 'CNV': [], 'CNLOH': []}]}
> compass. plot_tree()
> ```
> 
> I would recommend the former.

Thank for your kindness reply and consideration. Many thanks!
