### ISSUE TITLE
Visualizing CNVs in a heatmap with features = 'positions'

### ISSUE THREAD

**Issue by eroesti** [MissionBio/mosaic#3]
Hi, I have a question regarding the visualization of CNVs.

I have assigned the DNA labels to the sample.cnv onbject as followed:

`sample.cnv.set_labels(filtered_dna.get_labels())`
`sample.cnv.set_palette(filtered_dna.get_palette())`

I would like to visualize the heatmap with features ordered by chromosomes and genes, however only ordering by default amplicons works:

`sample.cnv.heatmap('ploidy', features=sample.cnv.ids())`

When adjusting the command with features='positions' or features='genes' doesnt work and result in the following error:

`Not all the given features were found in the assay ids.`

How do the labels need to be assigned in order to work? Thanks in advance!!

**Comment by arribasm** [comment]
We're unable to reproduce the error. Can you let us know what version you are using? Are you able to view by genes and positions prior to assigning labels?

**Comment by eroesti** [comment]
Hi, I am using python 3.8.5.

I am also not able to visualize genes and positions before assigning labels.

My analysis was performed as follow if it can help:
- normalize counts with `sample.cnv.normalize_reads()`
- compute ploidy with `sample.cnv.compute_ploidy(diploid_cells=clone_1_barcodes, normalized_counts='normalized_counts')`
- assign the label that were given in sample.dna `sample.cnv.set_labels(filtered_dna.get_labels())
sample.cnv.set_palette(filtered_dna.get_palette())`
-  the only heatmap I could be able to get is with the following command: `sample.cnv.heatmap('ploidy', features=sample.cnv.ids())`

Previous to the CNV analysis the clone 1 that was assigned to diploid cells was label with `clone_1_barcodes = filtered_dna.barcodes('1')`

Any suggestions?

Thanks in advance!!

**Comment by MBSupport** [comment]
The issue may be from a difference in the barcodes present in the CNV data frame and the DNA data frame. You may need to run a line of code to subset the CNV barcodes to be equal to the DNA barcodes if any barcodes were dropped from the DNA frame. 
For example 
`sample.cnv = sample.cnv[filtered_dna.barcodes(),:]`
If this is not helping, you can email your entire notebook to support@missionbio.com so that we can review from the start.

**Comment by MBSupport** [comment]
To pull the annotations for the genes and chromosome locations the code will pull from the Mission Bio API, https://api.missionbio.io. Please make sure that this address is not being blocked by your institution and that you have an internet connection while running the code.

**Comment by eroesti** [comment]
Thank you @MBSupport for the help, that was indeed helping! On another note, I have sent my script to support@missionbio.com as I am having some troubles with another more complex graph, I would be very grateful if you could have a look. Thank you in advance!!:)
